from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('selection',views.selection,name='selection'),
    path('registrar/usuario',views.registrar_usuario,name='registrar_usuario'),
    path('registrar/moderador',views.registrar_moderador,name='registrar_moderador'),
    path('recipe/create', views.create_recipe,name='create_recipe'),
    path('recipes/list', views.list_recipes, name="list_recipes"),
    path('recipe/<int:recipe>',views.view_recipe,name="recipe"),
    path('recipe/search-advance/',views.advance_search_recipe,name='advance_search_recipe'),
    path('recipe/update/<int:recipe_id>',views.recipe_update,name='recipe_update'),
    path('recipe/delete/<int:recipe_id>',views.recipe_delete,name='recipe_delete'),
    path('ingredient/create', views.create_ingredient,name='create_ingredient'),
    path('ingredient/list', views.list_ingredient, name="list_ingredient"),
    path('ingredient/<int:ingredient>',views.view_ingredient,name="ingredient"),
    path('ingredient/search-advance/',views.advance_search_ingredient,name='advance_search_ingredient'),
    path('ingredient/update/<int:ingredient_id>',views.ingredient_update,name='ingredient_update'),
    path('ingredient/delete/<int:ingredient_id>',views.ingredient_delete,name='ingredient_delete'),
    path('utensil/<int:utensil>',views.view_utensil,name="utensil"),
    path('utensil/create', views.create_utensil,name='create_utensil'),
    path('utensil/search-advance/',views.advance_search_utensil,name='advance_search_utensil'),
    path('utensil/update/<int:utensil_id>',views.utensil_update,name='utensil_update'),
    path('utensil/delete/<int:utensil_id>',views.utensil_delete,name='utensil_delete'),
    path('utensil/list', views.list_utensil, name="list_utensil"),
    path('category/<int:category>',views.view_category,name="category"),
    path('category/create', views.create_category,name='create_category'),
    path('category/search-advance/',views.advance_search_category,name='advance_search_category'),
    path('category/update/<int:category_id>',views.category_update,name='category_update'),
    path('category/delete/<int:category_id>',views.category_delete,name='category_delete'),
    path('category/list', views.list_category, name="list_category"),
    path('tag/<int:tag>',views.view_tag,name="tag"),
    path('tag/list', views.list_tag, name="list_tag"),
    path('tag/create', views.create_tag,name='create_tag'),
    path('tag/search-advance/',views.advance_search_tag,name='advance_search_tag'),
    path('tag/update/<int:tag_id>',views.tag_update,name='tag_update'),
    path('tag/delete/<int:tag_id>',views.tag_delete,name='tag_delete'),
    path('user/<int:user>',views.view_user,name="user"),
    path('user/list', views.list_user, name="list_user"),
    path('user/create', views.create_user,name='create_user'),
    path('user/search-advance/',views.advance_search_user,name='advance_search_user'),
    path('user/update/<int:user_id>',views.user_update,name='user_update'),
    path('user/delete/<int:user_id>',views.user_delete,name='user_delete'),
    path('recipes/url2/<int:year_recipe>/<int:month_recipe>', views.get_recipe_date,name='get_recipe_date'),
    path('recipes/url3/<str:theme>/', views.get_user_theme, name="get_user_theme"),
    path('category/<str:description>', views.get_category_recipe, name='get_category_recipe'),
    path('last-user-comment/<int:recipe>', views.get_last_user_recipe, name='get_last_user_recipe'),
    re_path(r'^filtro[0-9]$',views.recipes_no_comment,name='recipes_no_comment'),
    path('user/<int:id_author>/recipes',views.get_user,name='get_user'),
    path('get_recipe-ingredient',views.get_recipe_ingredient,name='get_recipe_ingredient'),
    path('get-recipe-name-description',views.get_recipe_name_description,name='get_recipe_name_description'),
    path('get-user-utensils',views.get_recipe_utensils,name="get_recipe_utensils"),
    
]
